GET http://localhost:7070/api/v1/pictures
###
GET http://localhost:7070/api/v1/pictures/1
###
###
POST http://localhost:7070/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "user4",
  "password": "user4"
}

###
POST http://localhost:7070/api/v1/pictures/user4
Accept: application/json
Content-Type: application/json
Authorization: "Baerer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjcGhidXNpbmVzcy5kayIsInN1YiI6InVzZXI0IiwiZXhwIjoxNzAzMjQwOTkzLCJyb2xlcyI6InVzZXIiLCJ1c2VybmFtZSI6InVzZXI0In0.WMjgz_lPYZU5Nxvwo6ljuzVC6em_jW8U3rpG7-M9nZ4"

{
    "url": "url for picture2",
    "alt": "alt for picture2"
}

###
GET http://localhost:7070/api/v1/pictures/admin1
Accept: application/json
Content-Type: application/json
Authorization: "Baerer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjcGhidXNpbmVzcy5kayIsInN1YiI6ImFkbWluMSIsImV4cCI6MTcwMjY0NDk3Mywicm9sZXMiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4xIn0.3QTeV6OsECf162tE6Uc38xc_iZTNoI4nGWgzoMq1TCU"
###
DELETE http://localhost:7070/api/v1/pictures/2
Accept: application/json
Content-Type: application/json
Authorization: "Baerer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjcGhidXNpbmVzcy5kayIsInN1YiI6InVzZXI0IiwiZXhwIjoxNzAzMjQwOTkzLCJyb2xlcyI6InVzZXIiLCJ1c2VybmFtZSI6InVzZXI0In0.WMjgz_lPYZU5Nxvwo6ljuzVC6em_jW8U3rpG7-M9nZ4"
###
POST http://localhost:7070/api/v1/ratings/2/3
Accept: application/json
Content-Type: application/json
Authorization: "Baerer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjcGhidXNpbmVzcy5kayIsInN1YiI6InVzZXI0IiwiZXhwIjoxNzAzMjQwOTkzLCJyb2xlcyI6InVzZXIiLCJ1c2VybmFtZSI6InVzZXI0In0.WMjgz_lPYZU5Nxvwo6ljuzVC6em_jW8U3rpG7-M9nZ4"
###
GET http://localhost:7070/api/v1/ratings/136
Accept: application/json
Content-Type: application/json
Authorization: "Baerer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjcGhidXNpbmVzcy5kayIsInN1YiI6ImFkbWluMSIsImV4cCI6MTcwMzE2NTg3Niwicm9sZXMiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4xIn0.xsgvBRuSyswUGvXsU69jw-f2dL0LPiwGBlGqMC4l-0k"