GET http://localhost:7070/api/v1/pictures
###
GET http://localhost:7070/api/v1/pictures/1
###
###
POST http://localhost:7070/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin1",
  "password": "admin1"
}

###
POST http://localhost:7070/api/v1/pictures/admin1
Accept: application/json
Content-Type: application/json
Authorization: "Baerer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjcGhidXNpbmVzcy5kayIsInN1YiI6ImFkbWluMSIsImV4cCI6MTcwMjQ4Mzk0MCwicm9sZXMiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4xIn0.aTD3UFOeXoCgqGTiUA2tVuZHRPkieu7Dl2g_1yFbEuk"

{
    "url": "url for picture",
    "alt": "alt for picture"
}