### Register user/admin
POST {{url}}/auth/register
Content-Type: application/json

{
  "userName": "admin_user",
  "userPassword": "admin123",
  "roleList": ["ADMIN"]
}

> {% client.global.set("token", response.body.token); %}

### Register user/user
POST {{url}}/auth/register
Content-Type: application/json

{
  "userName": "user",
  "userPassword": "user",
  "roleList": ["USER"]
}
> {% client.global.set("token", response.body.token); %}

### Register user_manager/manager
POST {{url}}/auth/register
Content-Type: application/json

{
  "userName": "test_manager",
  "userPassword": "manager",
  "roleList": ["MANAGER", "ADMIN"]
}

> {% client.global.set("token", response.body.token); %}

### Login as admin
POST {{url}}/auth/login
Content-Type: application/json

{
  "userName": "admin",
  "userPassword": "admin123"
}

> {% client.global.set("token", response.body.token); %}

### Login as user
POST {{url}}/auth/login
Content-Type: application/json

{
  "userName": "user",
  "userPassword": "user"
}

> {% client.global.set("token", response.body.token); %}

### Login as manager
POST {{url}}/auth/login
Content-Type: application/json

{
  "userName": "manager",
  "userPassword": "manager123"
}

> {% client.global.set("token", response.body.token); %}