// Hotel API

GET {{url}}/hotels

###

GET {{url}}/hotels/6

###

POST {{url}}/hotels
Content-Type: application/json

{
  "hotelName": "Radisson",
  "hotelAddress": "Sindelfingen",
  "hotelType": "BUDGET"
}

###

PUT {{url}}/hotels/200
Content-Type: application/json

{
  "hotelName": "Scandic",
  "hotelAddress": "Lyngby Hovedgade",
  "hotelType": "BUDGET"
}

###

DELETE {{url}}/hotels/54

###

// Room API

GET {{url}}/rooms

###

GET {{url}}/rooms/100

###

POST {{url}}/rooms/hotel/9
Content-Type: application/json

{
  "roomNumber": 11,
  "roomPrice": 1150,
  "roomType": "SINGLE"
}
